
[[navbar]]
  identifier = "why"
  name = "Why?"
  url = "/why/"
  weight = 1
[[navbar]]
  identifier = "vision"
  name = "Our Vision"
  url = "/our-vision/"
  weight = 2
[[navbar]]
  identifier = "supporters"
  name = "Supporters"
  url = "/supporters/"
  weight = 3
[[navbar]]
  identifier = "take-action"
  name = "Take Action"
  url = "/take-action/"
  weight = 4